### ISSUE TITLE
How can i add multiple layer() image with this？

### ISSUE THREAD

**Issue by AmazingMachine** [rahulshah456/LiveSlider#2]
If you can develop a version of 'multiple layer() image' to us, we can pay you through github sponsor

**Comment by rahulshah456** [comment]
with multiple layers are you referring something similar to 3d parallax layered images

**Comment by AmazingMachine** [comment]
> are you referring something similar to 3d parallax layered images

yes

**Comment by rahulshah456** [comment]
okay, so this can be implemented in this project. I will try to consider this on the next update...

**Comment by AmazingMachine** [comment]
> okay, so this can be implemented in this project. I will try to consider this on the next update...

Thank you very much, but we did not find the sponsor button in your Github project

**Comment by AmazingMachine** [comment]
> okay, so this can be implemented in this project. I will try to consider this on the next update...
Please add sponsor button to facilitate our future cooperation

**Comment by AmazingMachine** [comment]
> okay, so this can be implemented in this project. I will try to consider this on the next update...

Please add sponsor button to facilitate our future cooperation

**Comment by rahulshah456** [comment]
Github sponsorship is not available in my country yet.
