### ISSUE TITLE
Where is the apk?

### ISSUE THREAD

**Issue by Aleks-Levet** [rahulshah456/LiveSlider#4]

**Comment by rahulshah456** [comment]
This application was previously published on the Play Store, which is why I didn't create any releases here. However, you can always build the app from Android Studio and customize it as you like.

**Comment by Aleks-Levet** [comment]
Could you build it for me? 🥺
Installing the whole android studio just to build one app is like overkill for me...
I have a nothing phone 1 btw if you need that info...

**Comment by rahulshah456** [comment]
I understand that installing Android Studio can be a hassle. I’ll build the app for you this weekend and provide the APKs. 
Just give me a little time! 😊

**Comment by Aleks-Levet** [comment]
hi! I'm writing this just to remind you of this. (just in case you forgot)

**Comment by Aleks-Levet** [comment]
Hey @rahulshah456 , have you done it yet?

**Comment by rahulshah456** [comment]
Yeah man, I’ll update you soon! I’m just working on some changes to the storage API for Android 14 right now. Thanks for your patience!

Btw, have you used this app before?

**Comment by Aleks-Levet** [comment]
I haven't used the app before, I tried pallax, but it doesn't fit my needs... Your app has exactly all the features I wanted to have, so I wanted to try it!

**Comment by Aleks-Levet** [comment]
Hey, have you done it yet? (Sorry i'm too impatient)

**Comment by rahulshah456** [comment]
I've just released a new APK! Please note that it might be missing some features or may experience crashes, as I didn't have time for thorough testing. A complete build will be available next weekend. 
Thanks for your understanding! ✌️😊

**Comment by Aleks-Levet** [comment]
Hey! I didn't expect it to work THAT well! It is perfect, exactly what I needed, with no other useless features!

The only weird thing that I'm facing is that I can't edit a playlist but I don't care that much cuz I don't need to edit a playlist every day...

Best wallpaper app I've ever tried for sure! And I tried a lot of things!

If I post this on Reddit you'll get many downloads!

**Comment by rahulshah456** [comment]
Closing this issue since the latest APKs are now included with each release.
